# Generated by Django 4.0.3 on 2022-03-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
