# Generated by Django 4.0.3 on 2022-03-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0004_students_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='created',
        ),
    ]
