# Generated by Django 4.0.3 on 2022-03-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0008_alter_students_fichier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fichier',
            new_name='fishier',
        ),
    ]
