# Generated by Django 4.0.3 on 2022-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0009_rename_fichier_students_fishier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='fishier',
            field=models.FileField(upload_to='media/photos/'),
        ),
    ]
