# Generated by Django 4.0.3 on 2022-03-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0010_alter_students_fishier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='surname',
        ),
    ]
