# Generated by Django 4.0.3 on 2022-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0011_remove_students_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='fishier',
            field=models.FileField(upload_to='photos'),
        ),
    ]
