# Generated by Django 4.0.3 on 2022-03-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0013_students_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fishier',
            new_name='fichier',
        ),
        migrations.AddField(
            model_name='students',
            name='cv',
            field=models.FileField(default=1, upload_to='cv'),
            preserve_default=False,
        ),
    ]
