# Generated by Django 4.0.3 on 2022-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0014_rename_fishier_students_fichier_students_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
