# Generated by Django 4.0.3 on 2022-03-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0015_alter_students_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='cv',
            field=models.FileField(upload_to='cvs'),
        ),
    ]
