# Generated by Django 4.0.3 on 2022-03-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0016_alter_students_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='cv',
            field=models.FileField(upload_to='cv'),
        ),
    ]
