# Generated by Django 4.0.3 on 2022-03-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0017_alter_students_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fichier',
            new_name='image',
        ),
    ]
