# Generated by Django 4.0.3 on 2022-03-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonApp', '0019_alter_students_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='adresse',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=25),
        ),
    ]
